{% set name = "nbclassic" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6da2116ab76a63de62f42cf8ea93c9a0c564aaf8315834f7c52efb85b4640ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-nbclassic = nbclassic.notebookapp:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyter_server >=1.0.1,<2.0.0
    - notebook <7

test:
  imports:
    - nbclassic

about:
  home: http://github.com/jupyterlab/nbclassic
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Notebook as a Jupyter Server Extension.

  description: |
    Jupyter Notebook as a Jupyter Server Extension.
  dev_url: https://github.com/jupyterlab/nbclassic

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
