{% set name = "nbclassic" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 434228763f8cee754318cd6dfa42370db191af630dabab8e30bafc8c1aa3eee6

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  entry_points:
    - jupyter-nbclassic = nbclassic.notebookapp:main
    - jupyter-nbclassic-extension = nbclassic.nbextensions:main
    - jupyter-nbclassic-serverextension = nbclassic.serverextensions:main
    - jupyter-nbclassic-bundlerextension = nbclassic.bundler.bundlerextensions:main

requirements:
  host:
    - python
    - pip
    - babel
    - hatchling
    - hatch-jupyter-builder >=0.9.1
    - jupyter_server >=1.17
  run:
    - python
    - ipykernel
    - ipython_genutils
    - nest-asyncio >=1.5
    - notebook-shim >=0.2.3

{% set tests_to_skip = "" %}
# tornado.httpclient.HTTPClientError: HTTP 500: Internal Server Error
{% set tests_to_skip = '-k "not test_terminal_handler"' %}  # [win]

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-tornasync
    - pytest-jupyter
    - ripgrep
    - requests
  imports:
    - nbclassic
    - nbclassic.bundler.tools
    - nbclassic.config_manager
    - nbclassic.nbextensions
    - nbclassic.notebookapp
    - nbclassic.transutils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ tests_to_skip }}
    - jupyter nbclassic --help
    - jupyter nbclassic-extension --help
    - jupyter nbclassic-serverextension --help
    - jupyter nbclassic-bundlerextension --help
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | rg -ie "nbclassic.*enabled"  # [unix]
    - cat server_extensions | rg -ie "nbclassic.*OK"  # [unix]
    - cat server_extensions | rg -ie "notebook_shim.*enabled"  # [unix]
    - cat server_extensions | rg -ie "notebook_shim.*OK"  # [unix]
    - type server_extensions | rg -ie "nbclassic.*enabled"  # [win]
    - type server_extensions | rg -ie "nbclassic.*OK"  # [win]
    - type server_extensions | rg -ie "notebook_shim.*enabled"  # [win]
    - type server_extensions | rg -ie "notebook_shim.*OK"  # [win]  

about:
  home: https://github.com/jupyter/nbclassic
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Notebook as a Jupyter Server Extension.
  description: |
    This project prepares for a future where JupyterLab and other frontends
    switch to Jupyter Server for their Python Web application backend. Using
    this package, users can launch Jupyter Notebook, JupyterLab and other
    frontends side-by-side on top of the new Python server backend.
  dev_url: https://github.com/jupyter/nbclassic
  doc_url: https://nbclassic.readthedocs.io

extra:
  recipe-maintainers:
    - jasongrout
    - afshin
    - jtpio
    - bollwyvl
